--Flyway가 V1__create_schema.sql을 읽어서 연결된 PostgreSQL에 실행하도록 지시함.
-- 그 SQL에 create table이 있으므로 테이블이 생성됨
-- V1__create_schema.sql은 DB를 최초 구조인 버전 1로 만드는 SQL 명령 모음
-- Flyway의 기능
-- 1. DB에 연결: Flyway가 application.yml의 DataSource 설정을 이용해 PostgreSQL에 연결함
-- 2. migration 파일 탐색: src/main/resources/db/migration/ 경로에서 파일을 .sql파일을 찾음
-- 3. 실행기록확인: db의 flyway_schema_history 테이블에 어떤 migration이 실행됬는지 기록됨.
-- 4. 실행되지 않은 SQL만 실행: flyway_schema_history 테이블에 .sql 파일의 실행기록이 없으면 Flyway가 .sql을 읽어 PostgreSQL에 전달함
-- 그러니깐 새 DB 변경 사항이 생기면 기존의 .sql 파일을 수정하지 말고
-- migration 폴더에 새로운 .sql파일을 추가하면 됨. 그러면 flyway가 flyway_schema_history의 기록과 비교해서
-- 실행된 적 없는 수정 사항이 적혀져있는 .sql파일을 실행시킴-> 수정사항 반영됨
CREATE TABLE app_user (--db schema는 잘 만들어짐
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login_id VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uk_app_user_login_id UNIQUE (login_id)
);

CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_code VARCHAR(30) NOT NULL,
    name VARCHAR(200) NOT NULL,
    credits INTEGER NOT NULL,
    course_type VARCHAR(50) NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id),
    CONSTRAINT uk_course_course_code UNIQUE (course_code),
    CONSTRAINT chk_course_credits_positive CHECK (credits > 0)
);

CREATE TABLE completed_course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    CONSTRAINT pk_completed_course PRIMARY KEY (id),
    CONSTRAINT fk_completed_course_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_completed_course_course
        FOREIGN KEY (course_id) REFERENCES course (id),
    CONSTRAINT uk_completed_course_user_course UNIQUE (user_id, course_id)
);

CREATE TABLE course_section (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_id BIGINT NOT NULL,
    year INTEGER NOT NULL,
    semester VARCHAR(30) NOT NULL,
    section_number VARCHAR(30) NOT NULL,
    CONSTRAINT pk_course_section PRIMARY KEY (id),
    CONSTRAINT fk_course_section_course
        FOREIGN KEY (course_id) REFERENCES course (id),
    CONSTRAINT uk_course_section_course_term_number
        UNIQUE (course_id, year, semester, section_number),
    CONSTRAINT chk_course_section_year_positive CHECK (year > 0)
);

CREATE TABLE section_time (-- course_section 1----n section_time
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    section_id BIGINT NOT NULL,--예: CS200
    day_of_week VARCHAR(9) NOT NULL,--요일
    start_time TIME NOT NULL,--수업 시작 시간
    end_time TIME NOT NULL,--수업 종료 시간
    CONSTRAINT pk_section_time PRIMARY KEY (id),
    CONSTRAINT fk_section_time_section
        FOREIGN KEY (section_id) REFERENCES course_section (id),
    CONSTRAINT chk_section_time_day_of_week CHECK (
        day_of_week IN (
            'MONDAY',
            'TUESDAY',
            'WEDNESDAY',
            'THURSDAY',
            'FRIDAY',
            'SATURDAY',
            'SUNDAY'
        )
    ),
    CONSTRAINT chk_section_time_range CHECK (start_time < end_time)
);

CREATE TABLE interest_area (--interest area table schema 만들고 바로 데이터 삽입
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_interest_area PRIMARY KEY (id),
    CONSTRAINT uk_interest_area_name UNIQUE (name)
);

CREATE TABLE course_interest_area (
    course_id BIGINT NOT NULL,
    interest_area_id BIGINT NOT NULL,
    CONSTRAINT pk_course_interest_area PRIMARY KEY (course_id, interest_area_id),
    CONSTRAINT fk_course_interest_area_course
        FOREIGN KEY (course_id) REFERENCES course (id),
    CONSTRAINT fk_course_interest_area_interest_area
        FOREIGN KEY (interest_area_id) REFERENCES interest_area (id)
);

CREATE TABLE course_prerequisite (-- 선수과목을 나타내는 테이블
    course_id BIGINT NOT NULL, --과목
    prerequisite_course_id BIGINT NOT NULL, -- 선수과목
    relation_type VARCHAR(20) NOT NULL, --필수 선수, 선택 선수인지 표시
    CONSTRAINT pk_course_prerequisite
        PRIMARY KEY (course_id, prerequisite_course_id),
    CONSTRAINT fk_course_prerequisite_course
        FOREIGN KEY (course_id) REFERENCES course (id),
    CONSTRAINT fk_course_prerequisite_prerequisite_course
        FOREIGN KEY (prerequisite_course_id) REFERENCES course (id),
    CONSTRAINT chk_course_prerequisite_not_self
        CHECK (course_id <> prerequisite_course_id),
    CONSTRAINT chk_course_prerequisite_relation_type
        CHECK (relation_type IN ('PREREQUISITE', 'RECOMMENDED'))
);

INSERT INTO interest_area (name)
VALUES
    ('DATA_SCIENCE'),
    ('SYSTEM_NETWORK'),
    ('THEORY'),
    ('SOFTWARE_DESIGN'),
    ('SECURE_COMPUTING'),
    ('VISUAL_COMPUTING'),
    ('AI_INFORMATION_SERVICE'),
    ('SOCIAL_COMPUTING'),
    ('INTERACTIVE_COMPUTING');
