-- 데이터베이스의 최초 구조를 만드는 버전 1 마이그레이션이다.
-- Flyway는 application.yml의 DataSource로 PostgreSQL에 연결하고 db/migration에서
-- 마이그레이션 파일을 찾는다. 적용 결과는 flyway_schema_history에 기록하며, 기록이
-- 없는 파일만 실행한다. 이미 적용된 파일은 수정하지 않고 새 버전 파일을 추가해야 한다.

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login_id VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uk_app_user_login_id UNIQUE (login_id)
);

CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_code VARCHAR(30) NOT NULL,
    name VARCHAR(200) NOT NULL,
    credits INTEGER NOT NULL,
    course_type VARCHAR(50) NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id),
    CONSTRAINT uk_course_course_code UNIQUE (course_code),
    CONSTRAINT chk_course_credits_positive CHECK (credits > 0)
);

CREATE TABLE completed_course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    CONSTRAINT pk_completed_course PRIMARY KEY (id),
    CONSTRAINT fk_completed_course_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_completed_course_course
        FOREIGN KEY (course_id) REFERENCES course (id),
    CONSTRAINT uk_completed_course_user_course UNIQUE (user_id, course_id)
);

CREATE TABLE course_section (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_id BIGINT NOT NULL,
    year INTEGER NOT NULL,
    semester VARCHAR(30) NOT NULL,
    section_number VARCHAR(30) NOT NULL,
    CONSTRAINT pk_course_section PRIMARY KEY (id),
    CONSTRAINT fk_course_section_course
        FOREIGN KEY (course_id) REFERENCES course (id),
    CONSTRAINT uk_course_section_course_term_number
        UNIQUE (course_id, year, semester, section_number),
    CONSTRAINT chk_course_section_year_positive CHECK (year > 0)
);

-- 하나의 분반(course_section)은 여러 수업 시간(section_time)을 가질 수 있다.
CREATE TABLE section_time (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    section_id BIGINT NOT NULL,
    day_of_week VARCHAR(9) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    CONSTRAINT pk_section_time PRIMARY KEY (id),
    CONSTRAINT fk_section_time_section
        FOREIGN KEY (section_id) REFERENCES course_section (id),
    CONSTRAINT chk_section_time_day_of_week CHECK (
        day_of_week IN (
            'MONDAY',
            'TUESDAY',
            'WEDNESDAY',
            'THURSDAY',
            'FRIDAY',
            'SATURDAY',
            'SUNDAY'
        )
    ),
    CONSTRAINT chk_section_time_range CHECK (start_time < end_time)
);

-- 관심 분야 테이블은 아래 INSERT 문으로 초기 데이터까지 함께 넣는다.
CREATE TABLE interest_area (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_interest_area PRIMARY KEY (id),
    CONSTRAINT uk_interest_area_name UNIQUE (name)
);

CREATE TABLE course_interest_area (
    course_id BIGINT NOT NULL,
    interest_area_id BIGINT NOT NULL,
    CONSTRAINT pk_course_interest_area PRIMARY KEY (course_id, interest_area_id),
    CONSTRAINT fk_course_interest_area_course
        FOREIGN KEY (course_id) REFERENCES course (id),
    CONSTRAINT fk_course_interest_area_interest_area
        FOREIGN KEY (interest_area_id) REFERENCES interest_area (id)
);

-- 과목과 선수/권장 과목의 자기 참조 다대다 관계를 나타낸다.
CREATE TABLE course_prerequisite (
    course_id BIGINT NOT NULL,
    prerequisite_course_id BIGINT NOT NULL,
    relation_type VARCHAR(20) NOT NULL,
    CONSTRAINT pk_course_prerequisite
        PRIMARY KEY (course_id, prerequisite_course_id),
    CONSTRAINT fk_course_prerequisite_course
        FOREIGN KEY (course_id) REFERENCES course (id),
    CONSTRAINT fk_course_prerequisite_prerequisite_course
        FOREIGN KEY (prerequisite_course_id) REFERENCES course (id),
    CONSTRAINT chk_course_prerequisite_not_self
        CHECK (course_id <> prerequisite_course_id),
    CONSTRAINT chk_course_prerequisite_relation_type
        CHECK (relation_type IN ('PREREQUISITE', 'RECOMMENDED'))
);

INSERT INTO interest_area (name)
VALUES
    ('DATA_SCIENCE'),
    ('SYSTEM_NETWORK'),
    ('THEORY'),
    ('SOFTWARE_DESIGN'),
    ('SECURE_COMPUTING'),
    ('VISUAL_COMPUTING'),
    ('AI_INFORMATION_SERVICE'),
    ('SOCIAL_COMPUTING'),
    ('INTERACTIVE_COMPUTING');
