spring:
  application:
    name: timetable-recommender
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/timetable}
    username: ${DB_USERNAME:timetable}
    password: ${DB_PASSWORD:timetable}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080
